apiVersion: v1
kind: ConfigMap
metadata:
  name: speed-showdown-config
  labels:
    app: speed-showdown
data:
  vllm-url: "https://vllm-server-user-sbowerma.apps.ocp.cloud.rhai-tmm.dev/v1"
  standard-llm-url: "http://ollama-cpu:11434/v1"
  vllm-model: "RedHatAI/Meta-Llama-3.1-8B-Instruct-quantized.w4a16"
  standard-model: "llama3.1:8b"
